FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the source code
COPY . .

# Create a non-root user and set permissions
RUN addgroup -S appgroup && adduser -S appuser -G appgroup \
  && chown -R appuser:appgroup /app

# Switch to the non-root user
USER appuser

# Expose the app port
EXPOSE 8000

# Run the app
CMD ["node", "index.js"]
